# Generated by Django 3.2.25 on 2024-11-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shannonscoreweights',
            name='di_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='shannonscoreweights',
            name='irp_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='shannonscoreweights',
            name='oc_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='shannonscoreweights',
            name='tac_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='shannonscoreweights',
            name='u_weight',
            field=models.FloatField(default=0.2),
        ),
    ]
